### ISSUE TITLE
vsgconv command line with param -n 50000,parse output file name error, when converting OSG paged database.

### ISSUE THREAD

**Issue by simwangrui** [vsg-dev/vsgXchange#78] opened 2021-12-22 01:48 UTC
**Describe the bug**
I am working on Windows 10. I try to converting osg paged database into vsg paged database with command line: vsgconv input.ive output.vsgb -l 10 -n 50000. the initial output file name is not what I expected：
![image](https://user-images.githubusercontent.com/75113990/147019527-8c5c56b6-aac3-4be2-a9a4-a2a6afa1c5c8.png)
and the child node file name is missing an extension vsgb：
![image](https://user-images.githubusercontent.com/75113990/147021053-0f08304a-3f55-488d-922a-b23179256019.png)
finally, the database conversion failed.

if I using command line: vsgconv input.ive output.vsgb -l 10. It does working ok.
In addition, I must set the environment variable VSG_ FILE_ Path  to the path of the current OSG paging database，otherwise, the child node file of the paging database cannot be loaded:
![image](https://user-images.githubusercontent.com/75113990/147022792-a13d3e04-14c0-4e5c-bf2e-b10436f670df.png)

**Comment by robertosfield** [comment] 2021-12-22 08:59
Hii,

I can't figure out what you are describing.  What is the exact command line
you are using, and what is the root, and children filenames that are
generated?

Which version of the VSG are you build against?  I recently merged with VSG
and vsgXchange master changes to the way extensions are handled - a
vsg::fileExtension("myfile.ext") now returns ".ext" rather than "ext".
Perhaps there has been a related regression.

Cheers,
Robert.

**Comment by simwangrui** [comment] 2021-12-22 10:29
Set Environment variable VSG_ FILE_ Path as "D:\share\terrain\terrains",I run the command line with results as follows：
![image](https://user-images.githubusercontent.com/75113990/147076656-2af9c849-b78e-4529-bcd0-369c02710845.png)

Set Environment variable VSG_ FILE_ Path as "D:\work\lib\vsg_demo\vsgExamples\data",I run the command line with results as follows：
![image](https://user-images.githubusercontent.com/75113990/147077975-2433b357-720f-47a3-8dd7-2d333b6300bf.png)

VSG version: 0.2.2.5
vsgXchange version: 0.0.1

**Comment by robertosfield** [comment] 2021-12-22 11:47
Screen the screenshots it almost looks like you have a space between the
.ive and .vsgb extensions in the vsgconv.

As a general note, it's far better to copy and paste the command line used
directly into this Issue rather than using a screenshot.  This means I can
attempt to replicate it using the exact line you used rather than trying to
manually recreate it based on what the screenshot looks like it conveys.

**Comment by simwangrui** [comment] 2021-12-22 12:21
Hi,
I using the command line "vsgconv zws.ive zws.vsgb -l 5 -n 50000",  there is no space between the
.ive and .vsgb extensions. The screenshot seems to have spaces, but it doesn't.  My debugging shows that line parseing seems have some issues. with the above command line ,the outputFilename  is "50000",code in line 394 of the vsgconv.cpp .
vsg::Path outputFilename = arguments[argc - 1]; 

Because "50000" has no extension, subsequent processing is incorrect. when I using the command line "vsgconv zws.ive zws.vsgb -l 5" it work ok,but environment variable VSG_ FILE_ Path must setting to the path of the current OSG paging database.

Best wishes
ruiwang

**Comment by robertosfield** [comment] 2021-12-22 12:35
Thanks, that makes it clearer.

I have tracked down the "..vsgb" error and checked in a fix for this.  The
code was assuming the vsg::fileExtension() returned a "ext" extension, but
a recent change to the core VSG's convention has it now returning ".vsgb"
so no need to add the extra "." into the filename.

I'll next look into the -n issue.

**Comment by robertosfield** [comment] 2021-12-22 13:17
I have invested the -n issue and it turns out that vsgconv no longer needs or supports the -n <value> command line option, as required value is computed internally in vsgXchange/osg/OSG.cpp.  I have update the vsgXchange/README.md to remove the mention of the -n.  This commit that changes this is: 145b2d9b4e58e16d6ad3291fca8f183e53bf9cf1

The problem with the .extensions is in the commit: 871db18e8a8af5d504ac99c2657c1e5ea0259e6d

With these two fixes I believe all the problems reported in this Issue are now fixed.

**Closed by robertosfield** 2021-12-22 13:17 UTC
