### ISSUE TITLE
Windows configuration broken

### ISSUE THREAD

**Issue by rainergericke** [vsg-dev/vsgXchange#50] opened 2021-09-15 16:47 UTC
Cannot configure vsgXchange due to following errors:

Determining if the include file pthread.h exists failed with the following output:
Change Dir: C:/Users/raine/Documents/Arbeit/build/CMakeFiles/CMakeTmp

Run Build Command(s):C:/PROGRA~2/MICROS~2/2019/COMMUN~1/Common7/IDE/COMMON~1/MICROS~1/CMake/Ninja/ninja.exe cmTC_7a047 && [1/2] Building C object CMakeFiles\cmTC_7a047.dir\Debug\CheckIncludeFile.c.obj

FAILED: CMakeFiles/cmTC_7a047.dir/Debug/CheckIncludeFile.c.obj 

C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\cl.exe  /nologo -DCMAKE_INTDIR=\"Debug\"  /DWIN32 /D_WINDOWS /W3  /MDd /Zi /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\cmTC_7a047.dir\Debug\CheckIncludeFile.c.obj /FdCMakeFiles\cmTC_7a047.dir\Debug\ /FS -c C:\Users\raine\Documents\Arbeit\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c

C:\Users\raine\Documents\Arbeit\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "pthread.h": No such file or directory
ninja: build stopped: subcommand failed.

The text above is from CMakeError.log.

cmake outputs on the commandline:
CMake Error at CMakeLists.txt:23 (vsg_setup_build_vars):
  Unknown CMake command "vsg_setup_build_vars".

Error remains when using VS2019 instead of ninja

Pretty strange: pthread.h exists, it was installed by vcpkg!.
[CMakeCache.txt](https://github.com/vsg-dev/vsgXchange/files/7171905/CMakeCache.txt)
[CMakeError.log](https://github.com/vsg-dev/vsgXchange/files/7171908/CMakeError.log)

**Comment by robertosfield** [comment] 2021-09-15 17:01
@rhabacker do you have an idea what might wrong in the vsg_setup_build_vars macro that could cause this regression?

**Comment by robertosfield** [comment] 2021-09-15 17:16
I have a look through vsgExamples/CMakeLists.txt and the new vsgMacros.cmake that are invoked by I can't find any reference to searching for threading headers. 

Under a VS build I would have thought pthread.h wouldn't be checked for, but perhaps this is normal for CMake to go search for all possibilities.

The only place I can see Threads checked for is via the vsgConfig.cmake that will have been installed in lib/cmake/vsg/ by the VSG build and install.

**Comment by rhabacker** [comment] 2021-09-16 07:24
> Unknown CMake command "vsg_setup_build_vars".

The reason is that the vsg development package used is too old and does not provide this macro.

**Comment by rainergericke** [comment] 2021-09-16 08:14
So it's a vsg problem. Is it possible to provide a patch?

By the way: vsgImGui and vsgExamples also cannot be configured, same error occors.

**Comment by rhabacker** [comment] 2021-09-16 08:20
Updating VulkanSceneGraph source to version 0.1.6 (or using git master branch) should fix the issue https://github.com/vsg-dev/VulkanSceneGraph/releases/tag/VulkanSceneGraph-0.1.6.

**Comment by rainergericke** [comment] 2021-09-16 09:44
Thanks a lot! That's the solution. We can close this issue.

**Comment by robertosfield** [comment] 2021-09-16 13:45
Glad to hear the issue is now fixed.

**Closed by robertosfield** 2021-09-16 13:45 UTC
